"""
data_cleaning.py
=================
Bluestock Fintech - Mutual Fund Analytics Capstone
Day 2, Tasks 1-3: Clean nav_history, investor_transactions and
scheme_performance (with full validation logic), plus light, defensive
cleaning for the remaining 7 provided datasets so that ALL 10 cleaned
CSVs are ready for loading into SQLite (Task 5).

Input:  data/raw/*.csv          (untouched - never overwritten)
Output: data/processed/*_clean.csv  (10 files)
        reports/day2_cleaning_log.txt

Run from the project root:
    python scripts/data_cleaning.py
"""

from pathlib import Path
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
REPORTS_DIR = PROJECT_ROOT / "reports"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

LOG: list[str] = ["BLUESTOCK MF CAPSTONE — DAY 2 CLEANING LOG", "Generated by data_cleaning.py", ""]


def log(msg: str) -> None:
    print(msg)
    LOG.append(msg)


# ---------------------------------------------------------------------------
# Task 1: nav_history.csv
# ---------------------------------------------------------------------------
def clean_nav_history() -> pd.DataFrame:
    log("\n" + "=" * 70 + "\nTASK 1: Cleaning 02_nav_history.csv\n" + "=" * 70)

    df = pd.read_csv(RAW_DIR / "02_nav_history.csv")
    n_raw = len(df)

    df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=False)

    # Validate NAV > 0
    bad_nav = (df["nav"] <= 0) | df["nav"].isna()
    log(f"  Rows with NAV <= 0 or null: {bad_nav.sum()} (dropped)")
    df = df[~bad_nav]

    # Remove exact duplicates and (amfi_code, date) duplicates - keep first
    exact_dups = df.duplicated().sum()
    key_dups = df.duplicated(subset=["amfi_code", "date"]).sum()
    log(f"  Exact duplicate rows: {exact_dups} (dropped)")
    log(f"  Duplicate (amfi_code, date) rows: {key_dups} (kept first occurrence)")
    df = df.drop_duplicates().drop_duplicates(subset=["amfi_code", "date"], keep="first")

    df = df.sort_values(["amfi_code", "date"]).reset_index(drop=True)

    # Reindex every fund onto a continuous CALENDAR-day range (its own min->max
    # date) and forward-fill NAV, so weekends/holidays inherit the last
    # published NAV. is_actual_trading_day=1 marks rows that genuinely came
    # from the source file; 0 marks a forward-filled (non-trading) day.
    filled_frames = []
    total_filled = 0
    for code, grp in df.groupby("amfi_code"):
        grp = grp.set_index("date")
        full_range = pd.date_range(grp.index.min(), grp.index.max(), freq="D")
        grp_full = grp.reindex(full_range)
        n_filled = grp_full["nav"].isna().sum()
        total_filled += n_filled
        grp_full["is_actual_trading_day"] = (~grp_full["nav"].isna()).astype(int)
        grp_full["nav"] = grp_full["nav"].ffill()
        grp_full["amfi_code"] = code
        grp_full.index.name = "date"
        filled_frames.append(grp_full.reset_index())

    df_full = pd.concat(filled_frames, ignore_index=True)
    log(f"  Calendar-day reindex per fund: {total_filled} weekend/holiday gap(s) "
        f"forward-filled across {df['amfi_code'].nunique()} funds "
        f"({n_raw} source rows -> {len(df_full)} continuous daily rows).")

    # Daily return, computed on the now-continuous series per fund.
    df_full = df_full.sort_values(["amfi_code", "date"]).reset_index(drop=True)
    df_full["daily_return_pct"] = (
        df_full.groupby("amfi_code")["nav"].pct_change().mul(100).fillna(0).round(4)
    )
    df_full["nav"] = df_full["nav"].round(4)
    df_full["date"] = df_full["date"].dt.strftime("%Y-%m-%d")
    df_full["amfi_code"] = df_full["amfi_code"].astype(int)

    out_cols = ["amfi_code", "date", "nav", "daily_return_pct", "is_actual_trading_day"]
    df_full = df_full[out_cols]

    log(f"  Final shape: {df_full.shape}. NAV<=0 check post-clean: {(df_full['nav'] <= 0).sum()}.")
    return df_full


# ---------------------------------------------------------------------------
# Task 2: investor_transactions.csv
# ---------------------------------------------------------------------------
def clean_investor_transactions() -> pd.DataFrame:
    log("\n" + "=" * 70 + "\nTASK 2: Cleaning 08_investor_transactions.csv\n" + "=" * 70)

    df = pd.read_csv(RAW_DIR / "08_investor_transactions.csv")
    n_raw = len(df)

    # Fix / standardise date formats
    df["transaction_date"] = pd.to_datetime(df["transaction_date"], format="mixed", dayfirst=False)

    # Standardise transaction_type to {SIP, Lumpsum, Redemption}
    type_map = {"sip": "SIP", "lumpsum": "Lumpsum", "lump sum": "Lumpsum", "redemption": "Redemption"}
    df["transaction_type"] = df["transaction_type"].str.strip().str.lower().map(type_map)
    bad_type = df["transaction_type"].isna()
    log(f"  Unrecognised transaction_type values: {bad_type.sum()} (dropped)")
    df = df[~bad_type]

    # Validate amount > 0
    bad_amount = (df["amount_inr"] <= 0) | df["amount_inr"].isna()
    log(f"  Rows with amount_inr <= 0 or null: {bad_amount.sum()} (dropped)")
    df = df[~bad_amount]

    # Validate kyc_status enum
    valid_kyc = {"Verified", "Pending"}
    df["kyc_status"] = df["kyc_status"].str.strip()
    bad_kyc = ~df["kyc_status"].isin(valid_kyc)
    log(f"  Rows with kyc_status outside {valid_kyc}: {bad_kyc.sum()} (dropped)")
    df = df[~bad_kyc]

    # Defensive enum checks on the other categorical columns (flag, don't drop
    # unless invalid - these all passed clean on inspection)
    for col, valid_set in {
        "city_tier": {"T30", "B30"},
        "gender": {"Male", "Female"},
        "payment_mode": {"UPI", "Net Banking", "Mandate", "Cheque"},
    }.items():
        n_bad = (~df[col].isin(valid_set)).sum()
        log(f"  '{col}' values outside {valid_set}: {n_bad}")

    # Remove exact duplicate rows
    dup = df.duplicated().sum()
    log(f"  Exact duplicate rows: {dup} (dropped)")
    df = df.drop_duplicates()

    df = df.sort_values(["transaction_date", "investor_id"]).reset_index(drop=True)
    df.insert(0, "tx_id", range(1, len(df) + 1))  # surrogate key - raw file has none
    df["transaction_date"] = df["transaction_date"].dt.strftime("%Y-%m-%d")

    log(f"  Final shape: {df.shape} (from {n_raw} raw rows). Generated surrogate tx_id 1..{len(df)}.")
    return df


# ---------------------------------------------------------------------------
# Task 3: scheme_performance.csv
# ---------------------------------------------------------------------------
def clean_scheme_performance() -> pd.DataFrame:
    log("\n" + "=" * 70 + "\nTASK 3: Cleaning 07_scheme_performance.csv\n" + "=" * 70)

    df = pd.read_csv(RAW_DIR / "07_scheme_performance.csv")
    n_raw = len(df)

    numeric_cols = [
        "return_1yr_pct", "return_3yr_pct", "return_5yr_pct", "benchmark_3yr_pct",
        "alpha", "beta", "sharpe_ratio", "sortino_ratio", "std_dev_ann_pct",
        "max_drawdown_pct", "aum_crore", "expense_ratio_pct", "morningstar_rating",
    ]
    for col in numeric_cols:
        before_na = df[col].isna().sum()
        df[col] = pd.to_numeric(df[col], errors="coerce")
        new_na = df[col].isna().sum() - before_na
        if new_na:
            log(f"  '{col}': {new_na} non-numeric value(s) coerced to NaN")

    # Anomaly flags (reported, not auto-dropped - these are judgement calls
    # for an analyst, not hard data errors)
    flags = []
    flags.append(("negative_sharpe", (df["sharpe_ratio"] < 0).sum()))
    flags.append(("positive_max_drawdown (should be <= 0)", (df["max_drawdown_pct"] > 0).sum()))
    flags.append(("non_positive_std_dev (should be > 0)", (df["std_dev_ann_pct"] <= 0).sum()))
    flags.append(("beta_outside_0_to_2", (~df["beta"].between(0, 2)).sum()))
    flags.append(("morningstar_rating_outside_1_to_5", (~df["morningstar_rating"].between(1, 5)).sum()))
    out_of_range = ~df["expense_ratio_pct"].between(0.1, 2.5)
    flags.append(("expense_ratio_outside_0.1_to_2.5pct", out_of_range.sum()))

    for name, count in flags:
        log(f"  Anomaly check [{name}]: {count} row(s) flagged")

    dup = df.duplicated().sum()
    log(f"  Exact duplicate rows: {dup} (dropped)")
    df = df.drop_duplicates()

    log(f"  Final shape: {df.shape} (from {n_raw} raw rows). No automatic drops on flagged rows - "
        f"flags are informational since all checks passed clean on this dataset.")
    return df


# ---------------------------------------------------------------------------
# Light, defensive cleaning for the remaining 7 datasets
# ---------------------------------------------------------------------------
def clean_fund_master() -> pd.DataFrame:
    log("\n" + "=" * 70 + "\nTASK 1 (cont.): Cleaning 01_fund_master.csv (Day 1 anomaly fix)\n" + "=" * 70)
    df = pd.read_csv(RAW_DIR / "01_fund_master.csv")
    real_cols = [c for c in df.columns if not str(c).startswith("Unnamed")]
    n_raw, n_cols_raw = df.shape
    df = df[real_cols].dropna(subset=["amfi_code"]).copy()
    df["amfi_code"] = df["amfi_code"].astype(int)
    df["launch_date"] = pd.to_datetime(df["launch_date"], format="mixed", dayfirst=False).dt.strftime("%Y-%m-%d")
    dup = df.duplicated(subset=["amfi_code"]).sum()
    df = df.drop_duplicates(subset=["amfi_code"])
    log(f"  Dropped {n_raw - len(df)} blank row(s) and {n_cols_raw - len(real_cols)} junk column(s) "
        f"(the Day 1 structural defect). Duplicate amfi_codes: {dup}.")
    log(f"  Final shape: {df.shape}")
    return df


def clean_aum_by_fund_house() -> pd.DataFrame:
    log("\n--- Cleaning 03_aum_by_fund_house.csv ---")
    df = pd.read_csv(RAW_DIR / "03_aum_by_fund_house.csv")
    df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=False).dt.strftime("%Y-%m-%d")
    bad = (df["aum_crore"] <= 0) | df["aum_crore"].isna()
    log(f"  Non-positive/null aum_crore rows: {bad.sum()} (dropped)")
    df = df[~bad].drop_duplicates(subset=["fund_house", "date"])
    log(f"  Final shape: {df.shape}")
    return df


def clean_monthly_sip_inflows() -> pd.DataFrame:
    log("\n--- Cleaning 04_monthly_sip_inflows.csv ---")
    df = pd.read_csv(RAW_DIR / "04_monthly_sip_inflows.csv")
    df = df.drop_duplicates(subset=["month"]).sort_values("month").reset_index(drop=True)
    # Cross-check the provided yoy_growth_pct against a recomputed value
    recomputed = df["sip_inflow_crore"].pct_change(12).mul(100).round(2)
    mismatch = ((df["yoy_growth_pct"] - recomputed).abs() > 0.5) & df["yoy_growth_pct"].notna()
    log(f"  yoy_growth_pct: {df['yoy_growth_pct'].isna().sum()} null (expected - no year-ago value "
        f"for the first 12 months). Mismatches vs. recomputed YoY: {mismatch.sum()}.")
    log(f"  Final shape: {df.shape}")
    return df


def clean_category_inflows() -> pd.DataFrame:
    log("\n--- Cleaning 05_category_inflows.csv ---")
    df = pd.read_csv(RAW_DIR / "05_category_inflows.csv")
    df = df.drop_duplicates(subset=["month", "category"]).sort_values(["month", "category"]).reset_index(drop=True)
    log(f"  Final shape: {df.shape}")
    return df


def clean_industry_folio_count() -> pd.DataFrame:
    log("\n--- Cleaning 06_industry_folio_count.csv ---")
    df = pd.read_csv(RAW_DIR / "06_industry_folio_count.csv")
    df = df.drop_duplicates(subset=["month"]).sort_values("month").reset_index(drop=True)
    component_sum = df[["equity_folios_crore", "debt_folios_crore", "hybrid_folios_crore", "others_folios_crore"]].sum(axis=1)
    mismatch = (df["total_folios_crore"] - component_sum).abs() > 0.05
    log(f"  total_folios_crore vs. sum-of-components mismatch (>0.05cr): {mismatch.sum()} row(s)")
    log(f"  Reporting cadence is irregular (not strictly quarterly) - kept as-is, this reflects real AMFI publication dates.")
    log(f"  Final shape: {df.shape}")
    return df


def clean_portfolio_holdings() -> pd.DataFrame:
    log("\n--- Cleaning 09_portfolio_holdings.csv ---")
    df = pd.read_csv(RAW_DIR / "09_portfolio_holdings.csv")
    df["portfolio_date"] = pd.to_datetime(df["portfolio_date"], format="mixed", dayfirst=False).dt.strftime("%Y-%m-%d")
    bad_weight = ~df["weight_pct"].between(0, 100)
    log(f"  weight_pct outside 0-100: {bad_weight.sum()} (dropped)")
    df = df[~bad_weight].drop_duplicates(subset=["amfi_code", "stock_symbol", "portfolio_date"])
    totals = df.groupby("amfi_code")["weight_pct"].sum()
    log(f"  Per-fund weight_pct totals range {totals.min():.2f}% - {totals.max():.2f}%: "
        f"every fund's disclosed holdings sum to ~100% (full portfolio, not a top-N excerpt). "
        f"{(totals - 100).abs().gt(0.5).sum()} fund(s) deviate from 100% by more than 0.5pt (true anomaly threshold).")
    log(f"  Final shape: {df.shape}")
    return df


def clean_benchmark_indices() -> pd.DataFrame:
    log("\n--- Cleaning 10_benchmark_indices.csv ---")
    df = pd.read_csv(RAW_DIR / "10_benchmark_indices.csv")
    df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=False).dt.strftime("%Y-%m-%d")
    bad = (df["close_value"] <= 0) | df["close_value"].isna()
    log(f"  Non-positive/null close_value rows: {bad.sum()} (dropped)")
    df = df[~bad].drop_duplicates(subset=["date", "index_name"])
    log(f"  Final shape: {df.shape}")
    return df


def main() -> None:
    outputs = {
        "01_fund_master_clean.csv": clean_fund_master(),
        "02_nav_history_clean.csv": clean_nav_history(),
        "03_aum_by_fund_house_clean.csv": clean_aum_by_fund_house(),
        "04_monthly_sip_inflows_clean.csv": clean_monthly_sip_inflows(),
        "05_category_inflows_clean.csv": clean_category_inflows(),
        "06_industry_folio_count_clean.csv": clean_industry_folio_count(),
        "07_scheme_performance_clean.csv": clean_scheme_performance(),
        "08_investor_transactions_clean.csv": clean_investor_transactions(),
        "09_portfolio_holdings_clean.csv": clean_portfolio_holdings(),
        "10_benchmark_indices_clean.csv": clean_benchmark_indices(),
    }

    log("\n" + "=" * 70 + "\nSUMMARY\n" + "=" * 70)
    for name, df in outputs.items():
        out_path = PROCESSED_DIR / name
        df.to_csv(out_path, index=False)
        log(f"  {name:38s} -> {df.shape[0]:6d} rows x {df.shape[1]} cols")

    log_path = REPORTS_DIR / "day2_cleaning_log.txt"
    log_path.write_text("\n".join(LOG), encoding="utf-8")
    print(f"\nAll 10 cleaned CSVs written to {PROCESSED_DIR}")
    print(f"Cleaning log written to {log_path}")


if __name__ == "__main__":
    main()
